AWSTemplateFormatVersion: 2010-09-09
Description: "Guidance for AWS and Salesforce Integrations - EDA with HTTP Proxy and Amazon Kinesis Data Streams"

Resources:
  KinesisStream:
    UpdateReplacePolicy: Retain
    Type: AWS::Kinesis::Stream
    DeletionPolicy: Delete
    Properties:
      StreamModeDetails:
        StreamMode: ON_DEMAND
      RetentionPeriodHours: 24
      DesiredShardLevelMetrics: []
      Name: sfdc-kds

  ApiGatewayHTTP:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Api
    DeletionPolicy: Delete
    Properties:
      RouteSelectionExpression: $request.method $request.path
      DisableExecuteApiEndpoint: false
      ProtocolType: HTTP
      Tags: {}
      Name: sfdc-proxy
      
  MyRoute:
    Type: AWS::ApiGatewayV2::Route
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      ApiId: !Ref ApiGatewayHTTP
      RouteKey: "POST /event"
      Target: !Sub "integrations/${KinesisIntegration}"
      AuthorizationType: AWS_IAM
  
  MyStage:
    Type: AWS::ApiGatewayV2::Stage
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      StageName: "$default"
      ApiId: !Ref ApiGatewayHTTP
  
  ApiGatewayV2Deployment003lj85o00Y7AMu:
    UpdateReplacePolicy: Retain
    Type: AWS::ApiGatewayV2::Deployment
    DeletionPolicy: Delete
    DependsOn:
      - MyRoute
    Properties:
      ApiId: !Ref ApiGatewayHTTP
      StageName: !Ref MyStage
      Description: Automatic deployment triggered by changes to the Api configuration
  
  KinesisIntegration:
    Type: AWS::ApiGatewayV2::Integration
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties:
      ApiId: !Ref ApiGatewayHTTP
      CredentialsArn: !GetAtt IAMRoleForAPI2KDS.Arn
      IntegrationType: AWS_PROXY
      IntegrationSubtype: Kinesis-PutRecord
      PayloadFormatVersion: "1.0"
      RequestParameters:
        StreamName: !Ref KinesisStream
        Data: $request.body.Data
        PartitionKey: sfdc

  IAMRoleForAPI2KDS:
    UpdateReplacePolicy: Retain
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    Properties:
      Path: "/service-role/"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AmazonKinesisFullAccess"
      MaxSessionDuration: 3600
      RoleName: "sfdc-role-api"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: "sts:AssumeRole"
          Effect: "Allow"
          Principal:
            Service: "apigateway.amazonaws.com"
            
